### ISSUE TITLE
CITAN Scopus API 

### ISSUE THREAD

**Issue by bw4sz** [Rexamine/CITAN#1]
Hi,

I'm not 100% clear on the goals of the CITAN package. My university just received scopus access. Should I be using CITAN to access the API directly by providing search terms. Or do i first execute a scopus search, download the data to a database and then use CITAN?

My goal is to compare academic departments by location and view the diversity of journals they publish in. 

Thanks for some first thoughts.

**Comment by gagolews** [comment]
Hi, the purpose is twofold. The first one is to provide implementation of various impact indices in R -- this part has already been moved to a separate package `agop`. The other one is to somehow automatize the processing of csv files with data exported from Scopus. There is no direct API access. And CITAN is rather oriented for single scientists, not on a macrolevel...
