### ISSUE TITLE
rsqlite_query_send

### ISSUE THREAD

**Issue by rcprati** [Rexamine/CITAN#2]
Hi,

I'm trying to use the package, but I'm getting the following error when using Scopus_ImportSources(conn):

Importing Scopus ASJC codes... 
Error in sqliteSendQuery(con, statement, bind.data) : 
  rsqlite_query_send: could not execute1: cannot start a transaction within a transaction
In addition: Warning message:
'dbBeginTransaction' is deprecated.
Use 'dbBegin' instead.
See help("Deprecated")

**Comment by gagolews** [comment]
This has now been fixed.
